"""Build the PDF reports (LaTeX) from the notebooks' results.json files.

1. Writes reports/generated/*.tex: one macro file per part holding every number the
   report text quotes, plus ready-made tables — all read from <part>/results.json, so the
   conclusions always match the metric tables (assignment rubric, section 7.1).
2. Compiles reports/{tabular,text,timeseries,G3-report}.tex twice with XeLaTeX.
3. Copies the PDFs to tabular/report.pdf, text/report.pdf, timeseries/report.pdf and G3-report.pdf.

Usage (from the repository root; needs a TeX Live installation with xelatex):
    python tools/build_reports.py            # all four PDFs
    python tools/build_reports.py tabular    # only one document
Re-run after re-running a notebook or adding a video link in tools/site_config.py,
then run tools/build_pages.py so the "PDF report" buttons point at the new files.
"""
import csv
import json
import math
import shutil
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path

from site_config import CONTRIBUTIONS, GITHUB_BLOB, MEMBERS, PAGES_URL, REPO, VIDEO_URLS

ROOT = Path(__file__).resolve().parents[1]
REP = ROOT / "reports"
GEN = REP / "generated"
BUILD = REP / "build"
NOTEBOOKS = {"tabular": "G3_Tabular_HotelBooking.ipynb", "text": "G3_Text_VnExpressNews.ipynb",
             "timeseries": "G3_TimeSeries_HanoiWeather.ipynb"}
DOCUMENTS = {"tabular": ROOT / "tabular/report.pdf", "text": ROOT / "text/report.pdf",
             "timeseries": ROOT / "timeseries/report.pdf", "G3-report": ROOT / "G3-report.pdf"}
TAB_NUMERIC_FEATURES = 26  # len(SKEWED) + len(WINSOR_ONLY) + len(OTHER_NUM) in the tabular notebook


# ---------- formatting helpers ----------
def esc(s):
    s = str(s)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\^{}")]:
        s = s.replace(a, b)
    return s


def minus(s):
    return s.replace("-", "−")


def f(x, d=3):
    return minus(f"{x:.{d}f}")


def sf(x, d=3):
    return minus(f"{x:+.{d}f}")


def pct(x, d=1):
    return minus(f"{x * 100:.{d}f}") + r"\%"


def n(x):
    return f"{int(round(x)):,}"


def long_date(iso):
    d = date.fromisoformat(iso)
    return f"{d.day} {d.strftime('%B %Y')}"


class Tex:
    """Collects \\newcommand macros for one part."""

    def __init__(self, prefix):
        self.prefix = prefix
        self.lines = []

    def __setitem__(self, name, value):
        self.lines.append(f"\\newcommand{{\\{self.prefix}{name}}}{{{value}}}")

    def write(self, path):
        path.write_text("% Generated by tools/build_reports.py — do not edit.\n" + "\n".join(self.lines) + "\n",
                        encoding="utf-8")


def write_table(path, colspec, header, rows, bold_rows=(), width=None):
    env = "tabularx" if width else "tabular"
    head = f"\\begin{{{env}}}{{{width}}}{{{colspec}}}" if width else f"\\begin{{tabular}}{{{colspec}}}"
    out = [head, r"\toprule", " & ".join(rf"\hd{{{h}}}" for h in header) + r" \\", r"\midrule"]
    for i, row in enumerate(rows):
        cells = [str(c) for c in row]
        if i in bold_rows:
            cells = [rf"\textbf{{{c}}}" for c in cells]
        out.append(" & ".join(cells) + r" \\")
    out += [r"\bottomrule", f"\\end{{{env}}}"]
    path.write_text("% Generated by tools/build_reports.py — do not edit.\n" + "\n".join(out) + "\n", encoding="utf-8")


def load(part):
    return json.loads((ROOT / part / "results.json").read_text(encoding="utf-8"))


def links(m, part):
    page, notebook, video = f"{PAGES_URL}{part}/", f"{GITHUB_BLOB}/{part}/{NOTEBOOKS[part]}", VIDEO_URLS.get(part)
    m["Page"], m["Notebook"] = rf"\url{{{page}}}", rf"\url{{{notebook}}}"
    m["Video"] = rf"\url{{{video}}}" if video else r"\textcolor{muted}{to be published}"
    video_link = rf"\href{{{video}}}{{Video presentation}}" if video else r"Video: \textcolor{muted}{to be published}"
    m["Links"] = rf"\href{{{page}}}{{Project page}}\quad·\quad\href{{{notebook}}}{{Notebook on GitHub}}\quad·\quad {video_link}"


# ---------- common ----------
def build_common():
    m = Tex("grp")
    m["Date"] = date.today().strftime("%B %Y")
    m["Lecturer"] = "Dr. Lê Thành Sách"
    m["Pages"] = rf"\url{{{PAGES_URL}}}"
    m["Repo"] = rf"\url{{https://github.com/{REPO}}}"
    m["MemberRows"] = " ".join(f"{i} & {esc(name)} & {sid} & {esc(CONTRIBUTIONS.get(sid, role))} \\\\"
                               for i, (name, sid, role, *_) in enumerate(MEMBERS, 1))
    m.write(GEN / "common.tex")


# ---------- tabular ----------
def build_tabular():
    r, m, out = load("tabular"), Tex("TB"), GEN / "tabular"
    out.mkdir(exist_ok=True)
    links(m, "tabular")
    ds, eda, val, test = r["dataset"], r["eda"], r["validation"], r["test"]
    m["RowsRaw"], m["ColsRaw"], m["RowsClean"] = n(ds["rows_raw"]), ds["cols_raw"], n(ds["rows_clean"])
    m["KeptPct"] = pct(ds["rows_clean"] / ds["rows_raw"])
    m["CancelRaw"], m["CancelClean"] = pct(ds["cancel_rate_raw"]), pct(ds["cancel_rate_clean"])
    m["NotCancelRaw"], m["NotCancelClean"] = pct(1 - ds["cancel_rate_raw"]), pct(1 - ds["cancel_rate_clean"])
    m["DupRows"], m["DupPct"] = n(ds["duplicates"]), pct(ds["duplicates"] / ds["rows_raw"])
    log = {row["reason"]: row["rows removed"] for row in eda["cleaning_log"]}
    m["DupRemoved"], m["ZeroGuests"], m["AdrBad"] = n(log["duplicate"]), n(log["0 guests"]), n(log["ADR negative or > 1000"])
    chk = eda["checks"]
    m["ZeroNights"] = n(chk["0-night bookings"])
    m["NFeatures"], m["NNumeric"] = ds["n_features"], TAB_NUMERIC_FEATURES
    m["NOneHot"] = ds["n_features"] - TAB_NUMERIC_FEATURES
    for k, v in r["split"].items():
        m[{"train": "Train", "validation": "Val", "test": "Test"}[k]] = n(v)
    m["NrBefore"], m["NrAfter"] = n(eda["nonrefund_before"]), n(eda["nonrefund_after"])
    m["NrDupPct"] = pct(1 - eda["nonrefund_after"] / eda["nonrefund_before"], 0)
    m["LeadShort"], m["LeadLong"] = pct(eda["lead_0_7"]), pct(eda["lead_over_365"])
    m["DepNR"], m["DepNo"] = pct(eda["deposit_cancel_rate"]["Non Refund"]), pct(eda["deposit_cancel_rate"]["No Deposit"])
    m["SpecialZero"], m["SpecialThree"] = pct(eda["special_0"]), pct(eda["special_3plus"])
    segr = eda["segment_cancel_rate"]
    m["SegGroups"], m["SegDirect"], m["SegCorporate"] = pct(segr["Groups"], 0), pct(segr["Direct"], 0), pct(segr["Corporate"], 0)
    mp = eda["missing_pct"]
    for col, name in [("company", "Company"), ("agent", "Agent"), ("country", "Country"), ("meal", "Meal")]:
        m[f"Miss{name}"] = f"{mp[col]:.2f}" + r"\%"
    sk = eda["skew"]
    m["SkewLeadBefore"], m["SkewLeadAfter"] = f(sk["lead_time"]["skew before"], 2), f(sk["lead_time"]["skew after"], 2)
    m["SkewAdrBefore"], m["SkewAdrAfter"] = f(sk["adr"]["skew before"], 2), f(sk["adr"]["skew after"], 2)
    rho = eda["spearman_with_target"]
    m["RhoLead"], m["RhoPrevCancel"] = sf(rho["lead_time"], 2), sf(rho["previous_cancellations"], 2)
    m["RhoSpecial"], m["RhoParking"] = sf(rho["total_of_special_requests"], 2), sf(rho["required_car_parking_spaces"], 2)

    names = {"Dummy (always 0)": "Dummy", "Logistic Regression": "Lr", "Decision Tree": "Dt", "Random Forest": "Rf",
             "HistGradientBoosting": "Hgb", "HGB (tuned)": "Tuned"}
    for k, short in names.items():
        for metric, mm in [("accuracy", "Acc"), ("f1", "F"), ("pr_auc", "PR"), ("roc_auc", "ROC")]:
            m[f"Val{short}{mm}"] = f(val[k][metric])
    m["TuneCV"] = f(r["tuning"]["best_cv_pr_auc"])
    bp = r["tuning"]["best_params"]
    m["TuneParams"] = (f"learning rate {bp['learning_rate']}, {bp['max_iter']} boosting iterations, "
                       f"{bp['max_leaf_nodes']} leaf nodes, at least {bp['min_samples_leaf']} samples per leaf, "
                       f"L2 penalty {bp['l2_regularization']}")
    rows = [("Dummy (always “not cancelled”)", "Dummy (always 0)"), ("Logistic Regression", "Logistic Regression"),
            ("Decision Tree", "Decision Tree"), ("Random Forest", "Random Forest"),
            ("HistGradientBoosting (HGB)", "HistGradientBoosting"), ("HGB, tuned", "HGB (tuned)")]
    write_table(out / "val.tex", "lrrrrrr", ["Model", "Accuracy", "Precision", "Recall", "F1", "ROC-AUC", "PR-AUC"],
                [[label] + [f(val[k][c]) for c in ["accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc"]] for label, k in rows],
                bold_rows=[5])

    pit = r["pitfalls"]
    leak, nodup, ok = pit["With target leakage"], pit["Duplicates not removed"], pit["Correct process (section 3)"]
    m["LeakF"], m["NodupF"], m["NodupPR"], m["CorrectF"], m["CorrectPR"] = f(leak["f1"]), f(nodup["f1"]), f(nodup["pr_auc"]), f(ok["f1"]), f(ok["pr_auc"])
    m["NodupGainF"], m["NodupGainPR"] = sf(nodup["f1"] - ok["f1"], 2), sf(nodup["pr_auc"] - ok["pr_auc"], 2)
    write_table(out / "pitfalls.tex", "lrrrr", ["Scenario", "Accuracy", "F1", "ROC-AUC", "PR-AUC"],
                [[label] + [f(row[c]) for c in ["accuracy", "f1", "roc_auc", "pr_auc"]] for label, row in
                 [("Leakage columns kept", leak), ("Duplicates not removed", nodup), ("Correct process (this report)", ok)]],
                bold_rows=[2])

    imb = r["imbalance"]
    thr_key = next(k for k in imb if k.startswith("F1-optimal"))
    m["Thr"] = f(r["threshold"], 2)
    for key, short in [("Default (threshold 0.5)", "Def"), ("class_weight=balanced", "Bal"), (thr_key, "Thr")]:
        for metric, mm in [("precision", "P"), ("recall", "R"), ("f1", "F"), ("pr_auc", "PR")]:
            m[f"Imb{short}{mm}"] = f(imb[key][metric])
    write_table(out / "imbalance.tex", "lrrrr", ["Strategy (validation set)", "Precision", "Recall", "F1", "PR-AUC"],
                [[label] + [f(imb[key][c]) for c in ["precision", "recall", "f1", "pr_auc"]] for label, key in
                 [("Default threshold 0.5", "Default (threshold 0.5)"), (r"\code{class\_weight=balanced}", "class_weight=balanced"),
                  (f"Threshold tuned for F1 ({f(r['threshold'], 2)})", thr_key)]], bold_rows=[2])

    lr, fin = test["Logistic Regression (baseline)"], test["HGB (tuned) + optimal threshold"]
    for short, row in [("Lr", lr), ("Fin", fin)]:
        for metric, mm in [("accuracy", "Acc"), ("precision", "P"), ("recall", "R"), ("f1", "F"), ("roc_auc", "ROC"), ("pr_auc", "PR")]:
            m[f"Test{short}{mm}"] = f(row[metric])
    m["GainF"], m["GainPR"], m["GainROC"] = sf(fin["f1"] - lr["f1"], 2), sf(fin["pr_auc"] - lr["pr_auc"], 2), sf(fin["roc_auc"] - lr["roc_auc"], 2)
    write_table(out / "test.tex", "lrrrrrr", ["Model (test set)", "Accuracy", "Precision", "Recall", "F1", "ROC-AUC", "PR-AUC"],
                [[label] + [f(row[c]) for c in ["accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc"]] for label, row in
                 [("Logistic Regression (baseline)", lr), (f"HGB tuned, threshold {f(r['threshold'], 2)}", fin)]], bold_rows=[1])
    (tn, fp), (fn, tp) = r["confusion_matrix"]
    m["TN"], m["FP"], m["FN"], m["TP"] = n(tn), n(fp), n(fn), n(tp)
    m["FPRate"], m["Positives"] = pct(fp / (tn + fp)), n(fn + tp)

    imp = r["importance"]
    order = list(imp)
    for col, name in [("lead_time", "Lead"), ("country", "Country"), ("market_segment", "Segment"),
                      ("total_of_special_requests", "Special"), ("deposit_type", "Deposit")]:
        m[f"Imp{name}"] = f(imp[col])
    m["ImpDepositRank"] = order.index("deposit_type") + 1

    seg = r["segments"]
    m["SegOnlineErr"], m["SegOnlineCancel"] = pct(seg["Online TA"]["error_rate"]), pct(seg["Online TA"]["cancel_rate"])
    m["SegDirectRecall"], m["SegCorpRecall"] = f(seg["Direct"]["recall"], 2), f(seg["Corporate"]["recall"], 2)
    m["SegGroupsRecall"], m["SegOfflineRecall"] = f(seg["Groups"]["recall"], 2), f(seg["Offline TA/TO"]["recall"], 2)
    write_table(out / "segments.tex", "lrrrr", ["Market segment", "Test bookings", "Cancel rate", "Error rate", "Recall"],
                [[esc(k), n(v["n"]), pct(v["cancel_rate"]), pct(v["error_rate"]), f(v["recall"], 2)] for k, v in seg.items()])
    m.write(GEN / "tabular.tex")


# ---------- text ----------
def build_text():
    r, m, out = load("text"), Tex("TX"), GEN / "text"
    out.mkdir(exist_ok=True)
    links(m, "text")
    ds, q = r["dataset"], r["quality"]
    m["RowsRaw"], m["RowsClean"], m["Removed"] = n(ds["rows_raw"]), n(ds["rows_clean"]), n(ds["rows_raw"] - ds["rows_clean"])
    m["Classes"] = len(ds["classes"])
    m["MissingDesc"], m["DupWithin"], m["MultiSection"], m["NFC"] = n(ds["missing_description"]), n(q["dup_within_section"]), n(q["multi_section_urls"]), n(q["nfc_changed"])
    m["MedTitle"], m["MedDesc"] = n(ds["median_title_len"]), n(ds["median_desc_len"])
    v = ds["vocab"]
    m["VocabUni"], m["VocabBi"], m["VocabChar"] = n(v["TF-IDF 1-gram"]), n(v["TF-IDF 1–2-gram"]), n(v["TF-IDF char 2–5"])
    m["SingleChar"] = n(ds["single_char_syllables_kept"])
    for k, name in [("train", "Train"), ("val", "Val"), ("test", "Test")]:
        m[name] = n(r["split"][k])
    with open(ROOT / "text/data/vnexpress_news.csv", encoding="utf-8") as fh:
        counts = Counter(row["category"] for row in csv.DictReader(fh))
    m["ClassMin"], m["ClassMax"] = min(counts.values()), max(counts.values())

    g = r["grid_val_macro_f1"]
    feats = [("BoW 1-gram", "Bow"), ("TF-IDF 1-gram", "Uni"), ("TF-IDF 1–2-gram", "Bi"), ("TF-IDF char 2–5", "Char")]
    models = [("Multinomial NB", "Nb"), ("Logistic Regression", "Lr"), ("Linear SVM", "Svm"), ("kNN (cosine, k=15)", "Knn")]
    for fk, fs in feats:
        for mk, ms in models:
            m[f"G{fs}{ms}"] = f(g[f"{fk} | {mk}"])
    gv = lambda fk, mk: g[f"{fk} | {mk}"]
    for mk, ms in models[1:]:
        m[f"GainTfidf{ms}"] = sf(gv("TF-IDF 1-gram", mk) - gv("BoW 1-gram", mk))
    bi_gains = [gv("TF-IDF 1–2-gram", mk) - gv("TF-IDF 1-gram", mk) for mk, _ in models]
    m["GainBiMin"], m["GainBiMax"] = sf(min(bi_gains)), sf(max(bi_gains))
    m["GainBiOverBowLr"] = sf(gv("TF-IDF 1–2-gram", "Logistic Regression") - gv("BoW 1-gram", "Logistic Regression"))
    m["GainBiOverBowSvm"] = sf(gv("TF-IDF 1–2-gram", "Linear SVM") - gv("BoW 1-gram", "Linear SVM"))
    best = max(g, key=g.get)
    m["GridBest"], m["GridBestF"] = esc(best.replace(" | ", " + ")), f(g[best])
    write_table(out / "grid.tex", "lrrrr", ["Representation", "Multinomial NB", "Logistic Reg.", "Linear SVM", "kNN (cosine)"],
                [[fk] + [(r"\textbf{%s}" % f(gv(fk, mk))) if f"{fk} | {mk}" == best else f(gv(fk, mk)) for mk, _ in models] for fk, _ in feats])
    m["RandomVal"] = f(r["random_val_macro_f1"])

    bp = r["tuning"]["best_params"]
    m["BestC"] = bp["clf__C"].rstrip("0").rstrip(".")
    m["BestNgram"] = bp["vec__ngram_range"].strip("()").replace(", ", "–")
    m["BestMinDf"], m["CvF"], m["TunedVal"] = bp["vec__min_df"], f(r["tuning"]["cv_macro_f1"]), f(r["tuning"]["val_macro_f1"])

    fl = r["fields_val_macro_f1"]
    m["HeadOnly"], m["LeadOnly"], m["Both"] = f(fl["Headline only"]), f(fl["Lead only"]), f(fl["Headline + lead"])
    m["LeadOverHead"], m["BothOverLead"] = sf(fl["Lead only"] - fl["Headline only"]), sf(fl["Headline + lead"] - fl["Lead only"])
    lc = sorted((int(k), v) for k, v in r["learning_curve"].items())
    mid = min(lc, key=lambda kv: abs(kv[0] - lc[-1][0] / 2))
    m["LcFirstN"], m["LcFirst"], m["LcMidN"], m["LcMid"] = n(lc[0][0]), f(lc[0][1]), n(mid[0]), f(mid[1])
    m["LcLastN"], m["LcLast"], m["LcLastGain"] = n(lc[-1][0]), f(lc[-1][1]), sf(lc[-1][1] - mid[1])

    c = r["comparison"]
    keys = [("Rand", "Stratified random baseline", "Random guess (stratified)"),
            ("Tfidf", "TF-IDF + Linear SVM (tuned)", "TF-IDF 1–3-gram + Linear SVM (tuned)"),
            ("Emb", "Embedding (e5-small) + LogReg", "Embedding (e5-small) + Logistic Regr."),
            ("Hyb", "Hybrid: TF-IDF ⊕ embedding + Linear SVM", "Hybrid: TF-IDF ⊕ embedding + Linear SVM")]
    cell = lambda x: "—" if x is None or (isinstance(x, float) and math.isnan(x)) else f(x)
    for short, k, _ in keys:
        m[f"{short}Val"], m[f"{short}Test"], m[f"{short}Acc"] = cell(c[k]["validation macro-F1"]), cell(c[k]["test macro-F1"]), cell(c[k]["test accuracy"])
    m["GainHyb"] = sf(c[keys[3][1]]["test macro-F1"] - c[keys[1][1]]["test macro-F1"])
    m["GainEmb"] = sf(c[keys[2][1]]["test macro-F1"] - c[keys[1][1]]["test macro-F1"])
    write_table(out / "comparison.tex", "lrrr", ["Approach", "Val. macro-F1", "Test macro-F1", "Test acc."],
                [[label, cell(c[k]["validation macro-F1"]), cell(c[k]["test macro-F1"]), cell(c[k]["test accuracy"])] for _, k, label in keys],
                bold_rows=[3])
    m["FinAcc"], m["FinF"] = f(r["test_accuracy"]), f(r["test_macro_f1"])
    pc = r["per_class_f1"]
    m["BestClass"], m["WorstClass"] = max(pc, key=pc.get), min(pc, key=pc.get)
    m["BestClassF"], m["WorstClassF"] = f(max(pc.values())), f(min(pc.values()))
    items = sorted(pc.items(), key=lambda kv: -kv[1])
    half = (len(items) + 1) // 2
    write_table(out / "perclass.tex", "lrlr", ["Section", "F1", "Section", "F1"],
                [[a[0], f(a[1]), b[0], f(b[1])] for a, b in zip(items[:half], items[half:])])
    write_table(out / "confusions.tex", "llr", ["True section", "Predicted as", "Test errors"],
                [[x["true"], x["predicted"], n(x["errors"])] for x in r["top_confusions"]])
    sims = list(r["centroid_similarity_top"].items())
    pair = lambda k: esc(k.replace(" ~ ", " and "))
    m["SimOnePair"], m["SimOne"], m["SimTwoPair"], m["SimTwo"] = pair(sims[0][0]), f(sims[0][1], 2), pair(sims[1][0]), f(sims[1][1], 2)
    m["NMis"] = n(r["n_misclassified"])
    write_table(out / "misclassified.tex", "Yll", ["Headline (Vietnamese)", "True", "Predicted"],
                [[esc(x["title"]), x["label"], x["predicted"]] for x in r["misclassified_examples"][:8]], width=r"\linewidth")
    write_table(out / "demo.tex", "Yl", ["Headline written by the group (not in the dataset)", "Predicted section"],
                [[esc(x["headline"]), x["predicted section"]] for x in r["demo"]], width=r"\linewidth")
    write_table(out / "topterms.tex", "lY", ["Section", "Top 8 discriminative n-grams (χ², training set)"],
                [[cls, ", ".join(esc(t) for t in terms)] for cls, terms in r["top_terms"].items()], width=r"\linewidth")
    m.write(GEN / "text.tex")


# ---------- time series ----------
def build_timeseries():
    r, m, out = load("timeseries"), Tex("TS"), GEN / "timeseries"
    out.mkdir(exist_ok=True)
    links(m, "timeseries")
    ds = r["dataset"]
    m["Days"], m["Vars"], m["MissingDates"] = n(ds["days"]), ds["variables"], n(ds["missing_dates"])
    m["Start"], m["End"] = long_date(ds["start"]), long_date(ds["end"])
    m["Trend"] = sf(ds["trend_c_per_decade"], 2)
    m["Coldest"], m["ColdestDate"] = f(ds["coldest"][1], 1), long_date(ds["coldest"][0])
    m["Hottest"], m["HottestDate"] = f(ds["hottest"][1], 1), long_date(ds["hottest"][0])
    m["Extremes"] = n(ds["extreme_days_z3"])
    an = r["annual"]
    m["FirstFive"], m["LastFive"], m["DeltaFive"] = f(an["first5"], 2), f(an["last5"], 2), sf(an["last5"] - an["first5"], 2)
    vals = {int(k): v for k, v in an["values"].items() if int(k) <= 2025}
    lo, hi = min(vals, key=vals.get), max(vals, key=vals.get)
    m["AnnualMin"], m["AnnualMinYear"], m["AnnualMax"], m["AnnualMaxYear"] = f(vals[lo], 1), lo, f(vals[hi], 1), hi
    se = r["seasons"]
    m["Summer"], m["Winter"], m["SeasonGap"] = f(se["summer_mean"], 1), f(se["winter_mean"], 1), f(se["summer_mean"] - se["winter_mean"], 0)
    m["JanStd"], m["JulStd"] = f(se["jan_std"], 2), f(se["jul_std"], 2)
    dtd = se["day_to_day_by_month"]
    m["DtdFeb"], m["DtdMar"], m["DtdJul"] = f(dtd["2"], 2), f(dtd["3"], 2), f(dtd["7"], 2)
    a = r["acf"]
    m["AcfYear"], m["AcfAnomOne"], m["AcfAnomSeven"] = f(a["lag365"], 2), f(a["anom_lag1"], 2), f(a["anom_lag7"], 2)
    cs, cx = r["cold_surge"], r["cold_surge_extra"]
    m["R"], m["NRise"] = f(cs["r_dP_dTnext_winter"], 2), n(cx["n_rise"])
    m["DTRise"], m["DTOther"] = sf(cs["mean_dT_after_rise"], 2), sf(cs["mean_dT_otherwise"], 2)
    m["PRise"], m["POther"], m["PRatio"] = pct(cx["p_drop2_rise"]), pct(cx["p_drop2_other"]), f(cx["p_drop2_rise"] / cx["p_drop2_other"], 1)

    imp = r["imputation_mae"]
    methods = ["Forward fill", "Linear interpolation", "Climatology", "Seasonal interpolation"]
    rows = []
    for gap, row in imp.items():
        best = min(row, key=row.get)
        rows.append([f"{gap} day" + ("s" if gap != "1" else "")] + [(r"\textbf{%s}" % f(row[k], 2)) if k == best else f(row[k], 2) for k in methods])
    write_table(out / "imputation.tex", "lrrrr", ["Gap length", "Forward fill", "Linear interp.", "Climatology", "Seasonal interp."], rows)
    m["ImpSeasOne"], m["ImpSeasThree"], m["ImpSeasSeven"] = f(imp["1"]["Seasonal interpolation"], 2), f(imp["3"]["Seasonal interpolation"], 2), f(imp["7"]["Seasonal interpolation"], 2)
    m["ImpLinOne"], m["ImpLinThree"], m["ImpLinSeven"] = f(imp["1"]["Linear interpolation"], 2), f(imp["3"]["Linear interpolation"], 2), f(imp["7"]["Linear interpolation"], 2)
    m["ImpClimFourteen"], m["ImpClimThirty"] = f(imp["14"]["Climatology"], 2), f(imp["30"]["Climatology"], 2)

    p = r["precip"]
    m["RainOutliers"], m["RainSkew"], m["RainSkewLog"] = n(p["iqr_outliers"]), f(p["skew"], 1), f(p["skew_log"], 2)
    m["RainMax"], m["RainMaxDate"] = f(p["max"], 0), long_date(p["max_date"])
    for k, name in [("train", "Train"), ("val", "Val"), ("test", "Test")]:
        m[name] = n(r["split"][k])
    m["Phi"] = f(r["phi"], 2)
    tu = r["tuning"]
    m["CvTuned"], m["CvDefault"] = f(tu["best_cv_mae_delta"]), f(tu["default_cv_mae_delta"])  # validation MAEs: ValTuned / ValFinal below

    val, test, final = r["validation"], r["test"], r["final_model"]
    short = {"Climatology": "Clim", "Persistence": "Persist", "Damped anomaly persistence": "Damped", "Ridge regression": "Ridge",
             "Random Forest": "Rf", "HGB (level)": "Level", "HGB ΔT (tuned)": "Tuned", final: "Final"}
    for k, s in short.items():
        m[f"Val{s}"] = f(val[k]["MAE"])
        m[f"Test{s}"] = f(test[k]["MAE"])
    m["ValSkill"], m["TestSkill"] = pct(val[final]["skill_vs_persistence"], 0), pct(test[final]["skill_vs_persistence"])
    m["TestRmse"], m["TestRtwo"] = f(test[final]["RMSE"]), f(test[final]["R2"])
    label = {"Climatology": "Climatology (seasonal normal)", "Persistence": "Persistence (tomorrow = today)",
             "Damped anomaly persistence": "Damped anomaly persistence", "Ridge regression": "Ridge regression",
             "Random Forest": "Random Forest", "HGB (level)": "HGB, temperature as target",
             "HGB ΔT (tuned)": "HGB, change as target, tuned", final: "HGB, change as target (final)"}
    order = ["Climatology", "Persistence", "Damped anomaly persistence", "Ridge regression", "Random Forest", "HGB (level)", "HGB ΔT (tuned)", final]
    write_table(out / "models.tex", "lrrrrr", ["Model", "Val MAE", "Test MAE", "Test RMSE", "Test R²", "Skill"],
                [[label[k], f(val[k]["MAE"]), f(test[k]["MAE"]), f(test[k]["RMSE"]), f(test[k]["R2"]), pct(test[k]["skill_vs_persistence"])] for k in order],
                bold_rows=[len(order) - 1])

    mo = r["test_mae_by_month"]
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    write_table(out / "months.tex", "l" + "r" * 12, ["Test MAE (°C)"] + months,
                [["Persistence"] + [f(mo[str(i)]["abs_err_persist"], 2) for i in range(1, 13)],
                 ["Final model"] + [(r"\textbf{%s}" % f(mo[str(i)]["abs_err_model"], 2)) if mo[str(i)]["abs_err_model"] < mo[str(i)]["abs_err_persist"]
                                    else f(mo[str(i)]["abs_err_model"], 2) for i in range(1, 13)]])
    for i, name in [(2, "Feb"), (3, "Mar"), (12, "Dec"), (4, "Apr"), (11, "Nov")]:
        m[f"Mo{name}Model"], m[f"Mo{name}Persist"] = f(mo[str(i)]["abs_err_model"], 2), f(mo[str(i)]["abs_err_persist"], 2)
    m["MonthsWorse"] = sum(mo[str(i)]["abs_err_model"] >= mo[str(i)]["abs_err_persist"] for i in range(1, 13))

    res = r["residual"]
    m["ResMean"], m["ResStd"] = sf(res["mean"], 2), f(res["std"], 2)
    worst = r["worst_days"]
    cold = [w for w in worst if w["change vs day before"] <= -4]
    m["WorstN"], m["WorstCold"] = len(worst), len(cold)
    m["WorstDropMin"], m["WorstDropMax"] = f(min(-w["change vs day before"] for w in cold), 1), f(max(-w["change vs day before"] for w in cold), 1)
    m["WorstErrMin"], m["WorstErrMax"] = f(min(w["error"] for w in cold), 1), f(max(w["error"] for w in cold), 1)
    write_table(out / "worst.tex", "lrrrrr", ["Date", "Actual", "Forecast", "Error", "1-day change", "Pressure change"],
                [[long_date(w["date"]), f(w["actual"], 1), f(w["forecast"], 1), sf(w["error"], 1), sf(w["change vs day before"], 1),
                  sf(w["pressure change on forecast day (hPa)"], 1)] for w in worst])

    hz = {int(k): v for k, v in r["horizon_mae"].items()}
    bases = ["Persistence", "Climatology", "Damped anomaly persistence"]
    useful = max([h for h, row in hz.items() if row[final] < min(row[b] for b in bases) - 0.01] or [0])
    m["Useful"] = useful
    cross = min(h for h, row in hz.items() if row["Persistence"] > row["Climatology"])
    m["PersistCross"], m["PersistCrossMae"], m["Clim"] = cross, f(hz[cross]["Persistence"]), f(hz[1]["Climatology"])
    for h in range(1, useful + 1):
        word = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven"][h]
        m[f"H{word}"], m[f"H{word}Base"] = f(hz[h][final]), f(min(hz[h][b] for b in bases))
    m["HLast"] = f(hz[max(hz)][final])
    rows = []
    for name in bases + [final]:
        cells = []
        for h in sorted(hz):
            best = min(hz[h], key=hz[h].get)
            cells.append((r"\textbf{%s}" % f(hz[h][name], 2)) if name == best else f(hz[h][name], 2))
        rows.append([label.get(name, name) if name != final else "Final model"] + cells)
    write_table(out / "horizon.tex", "l" + "r" * len(hz), ["Test MAE (°C)"] + [f"{h} d" for h in sorted(hz)], rows)

    imp = r["importance"]
    m["ImpAnom"], m["ImpWind"], m["ImpRain"], m["ImpCloud"], m["ImpDp"] = (f(imp[k]) for k in ["anom_0", "wind_cos", "rain_log_0", "cloud_0", "dp_1d"])
    m.write(GEN / "timeseries.tex")


def build_overview():
    tb, tx, ts = load("tabular"), load("text"), load("timeseries")
    lr, fin = tb["test"]["Logistic Regression (baseline)"], tb["test"]["HGB (tuned) + optimal threshold"]
    tf = tx["comparison"]["TF-IDF + Linear SVM (tuned)"]["test macro-F1"]
    write_table(GEN / "overview.tex", "lL{3.0cm}L{3.2cm}lrr",
                ["Part", "Task", "Dataset", "Test metric", "Baseline", "Ours"],
                [["Tabular", "Will a hotel booking be cancelled? (binary)", f"Hotel Booking Demand, {n(tb['dataset']['rows_raw'])} bookings",
                  "F1", f"{f(lr['f1'])} (Log. Reg.)", rf"\textbf{{{f(fin['f1'])}}}"],
                 ["Text", "Which of 10 sections is a news article in?", f"VnExpress, {n(tx['dataset']['rows_raw'])} articles (self-crawled)",
                  "macro-F1", f"{f(tf)} (TF-IDF + SVM)", rf"\textbf{{{f(tx['test_macro_f1'])}}}"],
                 ["Time series", "Hanoi's mean temperature tomorrow", f"Open-Meteo / ERA5, {n(ts['dataset']['days'])} days",
                  "MAE (°C)", f"{f(ts['test']['Persistence']['MAE'])} (persistence)", rf"\textbf{{{f(ts['test'][ts['final_model']]['MAE'])}}}"]])


# ---------- compile ----------
def compile_all(only=()):
    BUILD.mkdir(exist_ok=True)
    for doc, target in DOCUMENTS.items():
        if only and doc not in only:
            continue
        for _ in range(4):  # TOC and "Page X of Y" need extra passes
            proc = subprocess.run(["xelatex", "-interaction=nonstopmode", "-halt-on-error", f"-output-directory={BUILD.name}", f"{doc}.tex"],
                                  cwd=REP, capture_output=True, text=True)
            if proc.returncode != 0:
                tail = "\n".join(l for l in proc.stdout.splitlines() if l.startswith("!") or l.startswith("l."))
                sys.exit(f"xelatex failed on {doc}.tex:\n{tail or proc.stdout[-3000:]}")
            if "Rerun" not in (BUILD / f"{doc}.log").read_text(encoding="utf-8", errors="replace"):
                break
        log = (BUILD / f"{doc}.log").read_text(encoding="utf-8", errors="replace")
        missing = log.count("Missing character")
        overfull = log.count("Overfull \\hbox")
        shutil.copy(BUILD / f"{doc}.pdf", target)
        pages = subprocess.run(["pdfinfo", str(target)], capture_output=True, text=True).stdout if shutil.which("pdfinfo") else ""
        npages = next((l.split()[-1] for l in pages.splitlines() if l.startswith("Pages:")), "?")
        print(f"{target.relative_to(ROOT)}: {npages} pages, {missing} missing glyphs, {overfull} overfull lines")


if __name__ == "__main__":
    GEN.mkdir(parents=True, exist_ok=True)
    build_common()
    build_tabular()
    build_text()
    build_timeseries()
    build_overview()
    if "--no-compile" not in sys.argv:
        compile_all([a for a in sys.argv[1:] if not a.startswith("--")])
